ARG BASE_IMAGE=livepeer/ai-runner:live-multimedia
FROM ${BASE_IMAGE}

ENV PIP_PREFER_BINARY=1

# Install StreamDiffusion dependencies
RUN pip install --no-cache-dir \
    torch==2.1.0 \
    torchvision==0.16.0 \
    xformers \
    --index-url https://download.pytorch.org/whl/cu121
RUN pip install huggingface-hub==0.23.2

# Install StreamDiffusion
RUN pip install git+https://github.com/cumulo-autumn/StreamDiffusion.git@main#egg=streamdiffusion[tensorrt]

# Install TensorRT extension
RUN python -m streamdiffusion.tools.install-tensorrt