ARG BASE_IMAGE=livepeer/ai-runner:base
FROM ${BASE_IMAGE}

RUN pip install --no-cache-dir \
    transformers==4.43.0 \
    peft \
    deepcache \
    soundfile \
    g2p-en \
    # sentencepiece \
    # descript-audio-codec \
    # flash_attn \
    git+https://github.com/huggingface/parler-tts.git

CMD ["uvicorn", "app.main:app", "--log-config", "app/cfg/uvicorn_logging_config.json", "--host", "0.0.0.0", "--port", "8000"]
