ARG BASE_IMAGE=livepeer/ai-runner:live-base
FROM ${BASE_IMAGE}

# Create directory for ComfyUI custom nodes and models
RUN mkdir -p /comfyui/custom_nodes

# Install required Python version
ARG PYTHON_VERSION=3.11.10
RUN pyenv install $PYTHON_VERSION && \
    pyenv global $PYTHON_VERSION && \
    pyenv rehash

# Upgrade pip and install required packages
ARG PIP_VERSION=23.3.2
ENV PIP_PREFER_BINARY=1
RUN pip install --no-cache-dir --upgrade pip==${PIP_VERSION} setuptools==69.5.1 wheel==0.43.0

# Install Sam2 dependencies
RUN pip install --no-cache-dir torch==2.3.1 torchvision torchaudio

# Set TORCH_CUDA_ARCH_LIST environment variable, fixes build error in segment-anything-2-real-time
ENV TORCH_CUDA_ARCH_LIST="8.0+PTX"

# Install comfystream (which includes ComfyUI)
RUN pip install git+https://github.com/yondonfu/comfystream.git@53fa9133abd03227612ef8a16bb42100efe0f306
RUN git clone https://github.com/yondonfu/comfystream.git@53fa9133abd03227612ef8a16bb42100efe0f306 && \
    cd comfystream && \
    pip install -r requirements.txt && \
    cp -r nodes/tensor_utils /comfyui/custom_nodes/ && \
    cd ..

# Install ComfyUI_RyanOnTheInside custom node
RUN cd /comfyui/custom_nodes && \ 
    git clone -b disable_add_routes https://github.com/pschroedl/ComfyUI_RyanOnTheInside.git@c026fa8ab84d39d3f4bea62e27d1b6717ad16a19 && \
    cd ComfyUI_RyanOnTheInside && \
    pip install -r requirements.txt && \
    cd ..

# Install ComfyUI-SAM2-Realtime custom node
RUN cd /comfyui/custom_nodes && \
    git clone https://github.com/pschroedl/ComfyUI-SAM2-Realtime.git@8873c23a14ecba0e48a02b6ce2cfbc5b995f1da9 && \
    cd ComfyUI-SAM2-Realtime && \
    pip install -r requirements.txt && \
    cd ..

# Install ComfyUI-Depth-Anything-Tensorrt Node (https://github.com/yuvraj108c/ComfyUI-Depth-Anything-Tensorrt)
RUN cd /comfyui/custom_nodes && \
    git clone https://github.com/yuvraj108c/ComfyUI-Depth-Anything-Tensorrt.git@ede57bac05059731f955c1b1563af2c1947f999a && \
    cd ComfyUI-Depth-Anything-Tensorrt && \
    pip install -r requirements.txt && \
    cd ..

# Upgrade TensorRT to 10.6.0
RUN pip uninstall -y tensorrt && \
    pip install tensorrt==10.6.0

# Set the working directory for the custom nodes
WORKDIR /comfyui/custom_nodes

# Set up ComfyUI workspace
ENV COMFY_UI_WORKSPACE="/comfyui"
RUN ln -s /models/ComfyUI--models /comfyui/models
# TODO: Consider linking the custom nodes directory as well and set those up in the host, similar to the models directory