ARG PIPELINE=comfyui
ARG BASE_IMAGE=livepeer/ai-runner:live-base-${PIPELINE}
FROM ${BASE_IMAGE}

# Set environment variables
ENV MAX_WORKERS=1
ENV HUGGINGFACE_HUB_CACHE=/models
ENV DIFFUSERS_CACHE=/models
ENV MODEL_DIR=/models

# Copy application files
COPY app/ /app/app
COPY images/ /app/images
COPY bench.py /app/bench.py

WORKDIR /app

CMD ["uvicorn", "app.main:app", "--log-config", "app/cfg/uvicorn_logging_config.json", "--host", "0.0.0.0", "--port", "8000"]
