ARG BASE_IMAGE=livepeer/ai-runner:base
FROM ${BASE_IMAGE}

RUN pip install --no-cache-dir transformers==4.43.3 bitsandbytes==0.43.3 psutil==6.0.0

CMD ["uvicorn", "app.main:app", "--log-config", "app/cfg/uvicorn_logging_config.json", "--host", "0.0.0.0", "--port", "8000"]
