ARG BASE_IMAGE=livepeer/ai-runner:live-base
FROM ${BASE_IMAGE}

# Create directory for ComfyUI custom nodes and models
RUN mkdir -p /comfyui/custom_nodes

# Install required Python version
ARG PYTHON_VERSION=3.11.10
RUN pyenv install $PYTHON_VERSION && \
    pyenv global $PYTHON_VERSION && \
    pyenv rehash

# Upgrade pip and install required packages
ARG PIP_VERSION=23.3.2
ENV PIP_PREFER_BINARY=1
RUN pip install --no-cache-dir --upgrade pip==${PIP_VERSION} setuptools==69.5.1 wheel==0.43.0

# Install g++ compiler
# RUN apt-get update && apt-get install -y \
#     g++-11 \
#     && apt-get clean && rm -rf /var/lib/apt/lists/*
# ENV CXX=/usr/bin/g++-11

# Install Sam2 dependencies
RUN pip install --no-cache-dir torch==2.3.1 torchvision torchaudio

# Install comfystream (which includes ComfyUI)
RUN pip install git+https://github.com/yondonfu/comfystream.git
RUN git clone https://github.com/yondonfu/comfystream.git && \
    cd comfystream && \
    pip install -r requirements.txt && \
    cp -r nodes/tensor_utils /comfyui/custom_nodes/ && \
    cd ..

# Set TORCH_CUDA_ARCH_LIST environment variable, fixes docker build error 
# ENV TORCH_CUDA_ARCH_LIST="6.0 7.0 7.5 8.0 8.6+PTX"
# RUN pip install numpy ninja
RUN cd /comfyui/custom_nodes && \ 
    git clone -b disable_add_routes https://github.com/pschroedl/ComfyUI_RyanOnTheInside.git && \
    cd ComfyUI_RyanOnTheInside && \
    pip install -r requirements.txt && \
    cd ..

COPY ComfyUI-SAM2-Realtime /comfyui/custom_nodes/ComfyUI-SAM2-Realtime/

RUN cd /comfyui/custom_nodes && \
    # git clone https://github.com/pschroedl/ComfyUI-SAM2-Realtime.git && \
    cd ComfyUI-SAM2-Realtime && \
    pip install -r requirements.txt && \ 
    cd ..

# Install ComfyUI-SAM2-Realtime Node (https://github.com/pschroedl/ComfyUI-SAM2-Realtime)
# RUN pip install --no-cache-dir --no-build-isolation git+https://github.com/pschroedl/ComfyUI-SAM2-Realtime.git
# RUN cd /comfyui/custom_nodes && \
#     git clone https://github.com/pschroedl/ComfyUI-SAM2-Realtime.git && \
#     cd ComfyUI-SAM2-Realtime && \
#     pip install -r requirements.txt  && \
#     python setup.py clean && \
#     python setup.py build install && \
#     cp /comfyui/custom_nodes/comfystream/nodes/tensor_utils/* /comfyui/custom_nodes/comfystream && \
#     cd ..

# Set the working directory for the custom nodes
WORKDIR /comfyui/custom_nodes

# Set up ComfyUI workspace
ENV COMFY_UI_WORKSPACE="/comfyui"
RUN ln -s /models/ComfyUI--models /comfyui/models
# TODO: Consider linking the custom nodes directory as well and set those up in the host, similar to the models directory