ARG PIPELINE=sam2
ARG BASE_IMAGE=livepeer/ai-runner:live-base
FROM ${BASE_IMAGE}

# Install latest stable Go version and system dependencies
RUN apt-get update && apt-get install -y \
    wget \
    libcairo2-dev \
    libgirepository1.0-dev \
    pkg-config \
    g++-12 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV CXX=/usr/bin/g++-12

# Install required Python version
ARG PYTHON_VERSION=3.10
RUN pyenv install $PYTHON_VERSION && \
    pyenv global $PYTHON_VERSION && \
    pyenv rehash

# Upgrade pip and install necessary setup packages
ARG PIP_VERSION=23.3.2
RUN pip install --no-cache-dir --upgrade pip==${PIP_VERSION} setuptools==69.5.1 wheel==0.43.0
RUN pip uninstall torch torchvision torchaudio xformers -y
RUN pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu122/torch_stable.html

# Set TORCH_CUDA_ARCH_LIST environment variable
# ENV TORCH_CUDA_ARCH_LIST="7.0;7.5;8.0;8.6"
ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0 7.5 8.0 8.6+PTX"

# Install any additional Python packages
COPY requirements.live-ai-sam2.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt
RUN pip install --no-cache-dir --no-build-isolation \
    git+https://github.com/pschroedl/segment-anything-2-real-time@notebook_test

#RUN pip install --no-cache-dir torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 xformers==0.0.27 git+https://github.com/facebookresearch/sam2.git@0f6515ae853c40420ea8e3dd250f8031bbf03023#egg=sam-2

# Set environment variables
ENV MAX_WORKERS=1
ENV HUGGINGFACE_HUB_CACHE=/models
ENV DIFFUSERS_CACHE=/models
ENV MODEL_DIR=/models

# Copy application files
COPY app/ /app/app
COPY images/ /app/images
COPY bench.py /app/bench.py

WORKDIR /app

CMD ["uvicorn", "app.main:app", "--log-config", "app/cfg/uvicorn_logging_config.json", "--host", "0.0.0.0", "--port", "8000"]