name: Build ai-runner base Docker image

on:
  pull_request:
    paths:
      - "runner/**"
      - "!runner/.devcontainer/**"
  push:
    branches:
      - main
    tags:
      - "*"
    paths:
      - "runner/**"
      - "!runner/.devcontainer/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ !((github.ref_type == 'branch' && github.ref_name == 'main') || github.ref_type == 'tag') }}

jobs:
  docker:
    name: Docker image generation
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository || github.event_name == 'workflow_dispatch'
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          # Check https://github.com/livepeer/go-livepeer/pull/1891
          # for ref value discussion
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CI_DOCKERHUB_USERNAME }}
          password: ${{ secrets.CI_DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            livepeer/ai-runner
          tags: |
            type=sha
            type=ref,event=pr
            type=ref,event=tag
            type=sha,format=long
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}},prefix=v
            type=semver,pattern={{major}}.{{minor}},prefix=v
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=base,enable={{is_default_branch}}
            type=raw,value=${{ github.event.pull_request.head.ref }}
            type=raw,value=stable,enable=${{ startsWith(github.event.ref, 'refs/tags/v') }}

      - name: Build and push runner docker image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:runner"
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          file: "Dockerfile"
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=livepeerci/build:cache
          cache-to: type=registry,ref=livepeerci/build:cache,mode=max

      - name: Notify new build upload
        run: curl -X POST https://holy-bread-207a.livepeer.workers.dev
